//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnitiyFrameWorkMVCKnockoutNinject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int Member_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string User_Name { get; set; }
        public System.DateTime Date_Joined { get; set; }
        public System.DateTime Date_Of_Birth { get; set; }
        public string Phone_Number { get; set; }
    }
}
