//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnitiyFrameWorkMVCKnockoutNinject.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SkillsDbEntities : DbContext
    {
        public SkillsDbEntities()
            : base("name=SkillsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Member> Members { get; set; }
        public DbSet<skill> skills { get; set; }
    
        public virtual int sp_skill_create(string skill_name, ObjectParameter iD)
        {
            var skill_nameParameter = skill_name != null ?
                new ObjectParameter("skill_name", skill_name) :
                new ObjectParameter("skill_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_skill_create", skill_nameParameter, iD);
        }
    
        public virtual int sp_skill_delete(Nullable<int> skill_id)
        {
            var skill_idParameter = skill_id.HasValue ?
                new ObjectParameter("skill_id", skill_id) :
                new ObjectParameter("skill_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_skill_delete", skill_idParameter);
        }
    
        public virtual ObjectResult<sp_skill_read_Result> sp_skill_read(Nullable<int> skill_id)
        {
            var skill_idParameter = skill_id.HasValue ?
                new ObjectParameter("skill_id", skill_id) :
                new ObjectParameter("skill_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_skill_read_Result>("sp_skill_read", skill_idParameter);
        }
    
        public virtual int sp_skill_update(Nullable<int> skill_id, string skill_name)
        {
            var skill_idParameter = skill_id.HasValue ?
                new ObjectParameter("skill_id", skill_id) :
                new ObjectParameter("skill_id", typeof(int));
    
            var skill_nameParameter = skill_name != null ?
                new ObjectParameter("skill_name", skill_name) :
                new ObjectParameter("skill_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_skill_update", skill_idParameter, skill_nameParameter);
        }
    
        public virtual ObjectResult<sp_skills_read_all_Result> sp_skills_read_all()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_skills_read_all_Result>("sp_skills_read_all");
        }
    }
}
